### ISSUE TITLE
I can't deploy this project on my website 

### ISSUE THREAD

**Issue by CASN** [viettools/checkdomain#81]
Hello, I am a student studying Python and the web, but I have never studied Python web projects before. I encountered some issues deploying your project on my website. Could you please guide me on how to fill out the form
![11111](https://github.com/viettools/checkdomain/assets/22930821/658a860c-96a8-4905-8ebc-b302650a68c6)

thanks for your time

**Comment by viettools** [comment]
@CrazyPeeta you must install libraries `pip install -r requirements.txt`. I don't know your environment. You should buy a VPS and run docker to build my project.

**Comment by CASN** [comment]
> @CrazyPeeta you must install libraries `pip install -r requirements.txt`. I don't know your environment. You should buy a VPS and run docker to build my project.

In fact, I can use vscode to use your project normally on Windows and the localhost:6996 works well, but I don't know how to deploy it to my server.
Can I only use Docker? Is there other way to deploy it? Also I will learn about Docker right now, thanks for your time.

**Comment by viettools** [comment]
@CrazyPeeta If you are a student and you are learning web.. You should learn Docker/Kubernetes. 
The environment from programming and product is the same, avoiding errors.
I built a real server in just 3 minutes and it was up and running (I haven't installed nginx yet..)

You can run my project through python's venv or your current python.

For Version 3.x.x you must run python3.11

**Comment by viettools** [comment]
My ISP dose not support IPv6. I ran my project with one command and waiting. It runs fast and error-free.
```
docker-compose -f docker-compose-ipv4.yml build
docker-compose -f docker-compose-ipv4.yml up -d
```
